export enum ScannedBarcodeType {
    CODE32 = "CODE 32",
    CODABAR = "Codabar",
    CODE128 = "Code 128",
    CODE39 = "Code 39",
    CODE93 = "Code 93",
    I2OF5 = "Interleaved 2 of 5",
    D2OF5 = "Discrete 2 of 5",
    IATA2OF5 = "Standard 2 of 5",
    CODE11 = "Code 11",
    MSI = "MSI Plesswy",
    EAN128 = "UCC/EAN-128",
    BOOKLANDEAN = "BOOKLAND EAN",
    TRIOPTIC39 = "TRIOPTIC39",
    UPCEAN = "UPC EAN",
    COUPON = "COUPON",
    DATAMATRIX = "DATAMATRIX",
    QRCODE = "QR code",
    MAXICODE = "Maxicode",
    USPOSTNET = "US Postnet",
    USPLANET = "US Planet",
    JAPPOSTAL = "Japan Postal",
    UKPOSTAL = "UK Postal",
    CANPOSTAL = "Can Postal",
    DUTCHPOSTAL = "Dutch Postal",
    AUSPOSTAL = "Aus Postal",
    SIGNATURE = "Signature",
    CUECODE = "CueCode",
    RSS14 = "RSS 14",
    TLC39 = "TLC 39",
    CHINESE_2OF5 = "Chinese 2of5",
    AZTEC = "Aztec",
    WEBCODE = "Webcode",
    PDF417 = "PDF 417",
    IMAGE = "Image",
    MATRIX_2OF5 = "Matrix 2of5",
}

// Define a type for the enum keys
export type ScannedBarcodeTypeKey = keyof typeof ScannedBarcodeType;